version: '3.3'

services:
  learn_postgresql:
# 不要每次都build,使用已经build好了的镜像
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: release.daocloud.io/demo/standalone_learn_postgresql:latest
    hostname: 'learn_postgresql'
    ports:
      - '65001:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'LearnPostgreSQL16'
      POSTGRES_DB: 'postgres'
      PGDATA: '/postgres/16/data'
      SERVER_NAME: 'pg_standalone'
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ~/LearnPostgreSQL/docker-vols/standalone:/postgres/16/data
